# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da0221584562843a0929e24e88475a933cb58b104fc42635c2f11baf66c3d79743cde11d7f4d464d251bda4fa256a5d6986b1612adb4188a09016bc12bf498c0

test:
  secret_key_base: 2d8319d93ecc090594a4c5de045c0c487d313bc4fd6d70b40ed6706d9bb6bc78844a38b5870c90e3d3cd304123d1f27efdb7b5c5ed8d17c45820419db32c1bd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
